# Generated by Django 4.1.1 on 2022-11-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='easy', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(default=200, help_text='this is the quiz!'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(help_text='required score in %'),
        ),
    ]
