# Generated by Django 4.1.1 on 2022-11-27 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_quiz_options_remove_quiz_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='required_score_to_pass',
        ),
    ]
