# Generated by Django 4.1.1 on 2022-11-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='correct',
        ),
        migrations.AddField(
            model_name='answer',
            name='Type_1A',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='Type_1B',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='Type_1C',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='Type_2A',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='Type_2B',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='Type_2C',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='Type_3A',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='Type_3B',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='Type_3C',
            field=models.BooleanField(default=False),
        ),
    ]
